image: maven:3-jdk-8

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: "-s .m2/settings.xml -B"

cache:
  paths:
    - .m2/repository/

stages:
  - test
  - archive
#   - deploy
  
test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS clean test

archive:
  stage: archive
  only:
    - tags
  script:
    - mvn $MAVEN_CLI_OPTS package
  artifacts:
    paths:
    - target/transdoc-cli-*.zip


# deploy:
#   stage: deploy
#   script:
#     - eval $(ssh-agent -s)
#     - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
#     - mkdir -p ~/.ssh
#     - chmod 700 ~/.ssh
#     - ssh-keyscan ${SSH_HOST} >> ~/.ssh/known_hosts
#     - chmod 644 ~/.ssh/known_hosts
#     - scp target/transdoc-cli-*.zip ${SSH_USER}@${SSH_HOST}:${SSH_PATH}
