image: maven:3-jdk-8

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: "-s .m2/settings.xml -e -B"

cache:
  paths:
    - .m2/repository/

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS clean test

deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS deploy
  only:
    - master
    - tags
