image: maven:3-jdk-8

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: "-s .m2/settings.xml -B"

cache:
  paths:
    - .m2/repository/
    - target/

stages:
  - build
  - test
  - archive
  
build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

archive:
  stage: archive
  script:
    - mvn $MAVEN_CLI_OPTS package
